### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#105]
Now that the project is being refined across multiple platforms, there are some important steps that are happening before logging starts. For example on Fly.io, we're creating a project and a database before building log dirs. These steps really should be logged.

- [ ] Log all steps of the deployment process, regardless of whether we've created a log dir yet.
- [ ] See [picologging](https://pypi.org/project/picologging/)

**Comment by ehmatthes** [comment]
Implementation
---

- [ ] Store early log entries in a string, and write them to the log file as soon as it's created.

**Comment by ehmatthes** [comment]
Other notes
---

- [ ] Consider using Django's logger, rather than general Python logging module.
    - [ ] See notes from djangocon, from [Django Logging Demysitified](https://2022.djangocon.us/talks/django-logging-demystified/)

**Comment by leetrout** [comment]
👋 I would love to help out remotely during the sprints (and after, as well).

If travel goes smoothly I will be around Thursday and Friday. Worst case I will only be around on Friday.

**Comment by ehmatthes** [comment]
Hi Lee, did you see the two discussions that were opened? If you want to jump in on those, we'll bring you on board with what's happening here.

**Comment by leetrout** [comment]
> Hi Lee, did you see the two discussions that were opened? If you want to jump in on those, we'll bring you on board with what's happening here.

I got in super late Thursday (2am local) and I am just now getting caught back up with everything. Sorry I missed the dedicated sprint working days. I followed up on the other threads... I had not seen those so thank you for linking!

**Comment by ehmatthes** [comment]
See #260.
