### ISSUE TITLE
Chronicle first use case with platform.sh

### ISSUE THREAD

**Issue by tataraba** [ehmatthes/django-simple-deploy#134]
I'm going to chronicle my steps using django-simple-deploy with very little experience.

Thought to use Fly.io for the test, as I've never used it before. Unfortunately, didn't have my credit card handy to verify my identity, so I'll try this one later. However, I do have a platform.sh account, so that will be my test.

First, I'll open up my django application and install the library... Using my django-slideshow demo app.

What follows is my experience and any questions/issues that come up.

**Comment by tataraba** [comment]
First step, adding `django-simple-deploy` to my project... easy enough:
![image](https://user-images.githubusercontent.com/46942991/197030460-a08578f4-5d14-49cc-a555-e5aa83a12c01.png)

**Comment by tataraba** [comment]
Make sure my project is running locally with no issue:

![image](https://user-images.githubusercontent.com/46942991/197030876-05bb858b-23ec-4356-96e0-c04e75111fff.png)

huzzah...

**Comment by tataraba** [comment]
The docs mention that I need the `platformshconfig` library, so I installed that as well:

![image](https://user-images.githubusercontent.com/46942991/197036361-643cb733-2cde-4844-a8cd-b78e487eaa36.png)

**Comment by tataraba** [comment]
Going to try the configuration-only deployment.

First, need to create a platform app... Made sure I could log in with the platform CLI. Ran the platform command and was prompted to log in (this is the intended step for logging in with the CLI)

Now, should be ready to create a platform app using:

```
platform create
```

Okay, looks like that worked.
![image](https://user-images.githubusercontent.com/46942991/197054958-b92bf987-4bbe-4544-8503-cb6411fa91b9.png)

**Comment by tataraba** [comment]
So now I can run the command:

```
python manage.py simple_deploy --platform platform_sh
```

Let's see what happened.

**Comment by tataraba** [comment]
Whoops.

![image](https://user-images.githubusercontent.com/46942991/197055443-f6652d76-99fd-4054-a8b0-bbe71729d0a3.png)


Looks like I didn't activate my virtual environment.... 🤦‍♂️

**Comment by tataraba** [comment]
Okay, after activating environment and running command, got this:

![image](https://user-images.githubusercontent.com/46942991/197055815-e180b48c-3313-4809-b6a6-0166ca180549.png)


Hmm...

**Comment by tataraba** [comment]
So going to commit my previous changes... These are related to adding django-simple-deploy and platformshconfig to my list of dependencies (`pyproject.toml`) and adding `simple_deploy` to my `INSTALLED_APPS`...

**Comment by tataraba** [comment]
Okay, so went ahead and committed to git with those things added and ran the command again....

![image](https://user-images.githubusercontent.com/46942991/197057933-8cf3575a-82d2-4141-9640-07ebe13ce1ab.png)


Looking good...

**Comment by tataraba** [comment]
Looks like since I am using PDM as my dependency manager, simple_deploy is finding my `pyproject.toml` file and determining that I am using Poetry instead of PDM. Using `pip show` doesn't work in this case ... (the pdm command would actually be `pdm list`)

![image](https://user-images.githubusercontent.com/46942991/197059619-c89657f6-643a-4392-9a8b-ef0113072c6e.png)

**Comment by ehmatthes** [comment]
> Okay, after activating environment and running command, got this:
> 
> ![image](https://user-images.githubusercontent.com/46942991/197055815-e180b48c-3313-4809-b6a6-0166ca180549.png)
> 
> Hmm...

Thanks! See #136.

**Comment by ehmatthes** [comment]
> Looks like since I am using PDM as my dependency manager, simple_deploy is finding my `pyproject.toml` file and determining that I am using Poetry instead of PDM. Using `pip show` doesn't work in this case ... (the pdm command would actually be `pdm list`)
> 
> ![image](https://user-images.githubusercontent.com/46942991/197059619-c89657f6-643a-4392-9a8b-ef0113072c6e.png)

Thanks again. See #137.
