### ISSUE TITLE
Heroku deployment missing database

### ISSUE THREAD

**Issue by jerivas** [ehmatthes/django-simple-deploy#141]
Here's the repo I'm trying to deploy: https://github.com/jerivas/blog-posts (branch `chapters`)

And a log of my first deployment to Heroku:

- Open existing Python project
- Switch to new branch `dsd`
- Create account on Heroku
- Visit DSD docs to know what's next
- See I need the Heroku CLI
- Install it, log in with `heroku auth:login`
- Verify `runserver` works. It does 
- `pip install django-simple-deploy`
- Ran `python manage.py simple_deploy --platform heroku`
- Lots of output, no errors. It says "Your project is now configured" near the end. It would be nice if output was collapsed under each "step", kinda like `docker build`. Also would appreciate some color and bold styles to clearly mark success
- Reviewed changes in the repo, looking good
- Committed the changes
- Ran `git push heroku main`, noticed Heroku picked up a different Python version
- Push failed because collectstatic doesn't work (that's on me). Heroku says I can disable collectstatic with `heroku config:set DISABLE_COLLECTSTATIC=1`. Did that
- Ran `git push heroku main` again. It worked! But it says I pushed from another branch
- Ran `git push heroku dsd:main`
- Got a 500 error message. It looks like the app is deployed but Heroku didn't deploy any databases

**Comment by ehmatthes** [comment]
I have cloned your project, modified it slightly for running on macOS, ie .gitignore, and pushed the main branch. i had the same results you saw; no errors in the push output, but a 500 error when I visit the page.
