### ISSUE TITLE
Write up guide for supporting a new platform

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#145]
A number of people are interested in building out support for a new platform. The actual scripting is not that difficult for people who already know a platform well; it's quite enjoyable and satisfying to make something that should be so reliable for end users.

Supporting a new platform does involve more than just writing code, though, there's some work to do in defining the fit between django-simple-deploy and any given platform. The project should support a variety of platforms, but not all platforms are well suited to simple_deploy.

- [x] Write up the detailed notes below.
- [x] Configure [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) (not needed)
- [ ] Respond to #132

**Comment by ehmatthes** [comment]
How to support a new platform
---

- [ ] Open an issue to track implementation for this platform.
- [ ] Write a brief rationale explaining why this platform is suitable for support by django-simple-deploy.
    - [ ] Is there a (mostly) scriptable deployment process for this platform? If there's too much work that needs to be done on the platform's web portal, it may not be suitable for support.
    - [ ] Most platforms ask you to make some decisions in the initial deployment process - which resources, which sizes of those resources, etc. Can you make, and justify, good default decisions for users? We can add some CLI args to give users some choice, but we don't want to replicate all the choices that the platform offers. We want to give a well-thought-out working initial deployment that they can then tweak. If a user knows enough specific choices to want a very specific config, they should probably do their deployment without simple_deploy.
    - [ ] How easily can we manage authentication? If users can log into a CLI and then we do all of our work without directing anything about authentication, it's probably a good fit. If we have to direct people to go get an API key, and then do something with that key, it may work. But if the steps become too long and create room for mistakes then maybe it's not a good fit.
    - [ ] What's the user's path to maintaining their deployment after their initial push? If it's reasonably straightforward, this is probably a good fit. If we can't easily describe how to do their next push, maybe it's not a good fit.
- [ ] Recommend running simple_deploy against a platform you already have an account on.
- [ ] Make sure you're comfortable immediately destroying your test project.
- [ ] Overview
    - [ ] What files will you modify?
    - [ ] What files will you create?
    - [ ] What tests will you write?
- [ ] What modifications do you need to make to `simple_deploy.py`?
    - [ ] As you're doing this, what architectural changes would you suggest in a rapidly evolving project? ie simple_deploy.py should probably be broken up sometime soon, perhaps into parts that are modified when new platforms are supported, and parts that are not?
    - [ ] import statements
    - [ ] Add an argument for your platform.
    - [ ] Instantiate a Deployer object.
- [ ] What does simple_deploy.py need to see in your deployer file?
    - [ ] Validation methods.
    - [ ] automate_all methods
    - [ ] anything else?

**Comment by glasnt** [comment]
> ## How to support a new platform

Could this be a template for new issues on this repo? Or do you propose another way to complete this checklist? 

(I'd like to create an issue and want to know what format I should use)

**Comment by ehmatthes** [comment]
Working notes
---

- Write this as an [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).
-
