### ISSUE TITLE
glasnt tries django-simple-deploy on heroku

### ISSUE THREAD

**Issue by glasnt** [ehmatthes/django-simple-deploy#152]
I tried out the heroku deployment on a very smol sample project https://github.com/glasnt/django-simple-project

I got the deployment happening, but with some limitations: 

The app deployed, but the admin looked funny (no static)

<img width="655" alt="Screen Shot 2022-10-22 at 12 11 55 pm" src="https://user-images.githubusercontent.com/813732/197359605-0d89f8e7-a1e1-4d49-8d94-60c8362b97e9.png">

I looked up the code and you're using `whitenoise`, but not configuring it. It's been [mentioned before](https://github.com/ehmatthes/django-simple-deploy/issues/7#issuecomment-962653071). 

I added this manually to my settings: 

```
import os
if 'ON_HEROKU' in os.environ:
   ...
+    # from https://whitenoise.evans.io/en/stable/#quickstart-for-django-apps, install whitenoise after SecurityMiddleware
+    i = MIDDLEWARE.index("django.middleware.security.SecurityMiddleware")
+    MIDDLEWARE.insert(i + 1,"whitenoise.middleware.WhiteNoiseMiddleware")
```

Heroku will automatically run collectstatic as part of the push: 

```
$ git commit -av
[main 1521f91] update heroku/whitenoise
 1 file changed, 8 insertions(+), 1 deletion(-)
$ git push heroku main
remote: -----> $ python manage.py collectstatic --noinput
remote:        131 static files copied to '/tmp/build_47e52420/staticfiles'.
```

So once I ran this, the admin looked okay again: 

<img width="655" alt="Screen Shot 2022-10-22 at 12 45 45 pm" src="https://user-images.githubusercontent.com/813732/197359625-29622da2-ac37-4454-81f3-b65f99fce5b9.png">

---

The other issue I had is that because blank database, I had no django admin login. 

I know I can fix this in heroku by running `heroku run python manage.py createsuperuser` and interactively re-create the admin user, which I did. 

---

My simple app contained a Procfile already, so this file was not overridden (but it also already ran locally). 

---

Still to do: 

* [x] write introduction in discussion  https://github.com/ehmatthes/django-simple-deploy/discussions/130#discussioncomment-3942286
* [x] try platform.sh #158, #159 
* [x] try fly.io #156 
   * [x] Noting differences
* [ ] new platform shenanigans

**Comment by ehmatthes** [comment]
Thank you! See #155.

**Comment by glasnt** [comment]
Pending creating a new issue for my new platform, I've completed all my tasks, so once I have that thread going I can close this issue.

**Comment by ehmatthes** [comment]
0.5.8 fixes the issue with static resources being made available for the admin site, and the larger whitenoise middleware issue. Thank you for the nice clean way to modify middleware as well!
