### ISSUE TITLE
Post deployment tasks, and createsuperuser

### ISSUE THREAD

**Issue by glasnt** [ehmatthes/django-simple-deploy#160]
I've mentioned this in all my run throughs so far (#152, #156, #158), and I think it needs a separate issue. 

The first time a user encounters `createsuperuser` in the canonical Django tutorial is mid way through [part 2](https://docs.djangoproject.com/en/4.1/intro/tutorial02/#creating-an-admin-user). Given a user's first simple-deploy will have a different database, I think this is one of things Important Things that should be included in the post-deployment output for each platform. 

I don't think django-simple-deploy should create an admin user for users, but I think it should detail how to run `manage.py` commands for the platform of choice. The `success_msg` should probably be updated to include at least how to invoke the console, if not a suggested command. 

Here's the full details for each current platform. 

* Heroku [`run`](https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-run):
  ```
  heroku run python manage.py createsuperuser
  ```
* Fly.io [`ssh console`](https://fly.io/docs/flyctl/ssh-console/): 
  ```
  flyctl ssh console
  # /code/manage.py createsuperuser
  ```
  * specifically because the default `pwd` of `ssh console` is `/`. 
* Platform.sh [ssh](https://docs.platform.sh/development/ssh.html): 
  ```
  platform ssh
  $ python manage.py createsuperuser
  ```

**Comment by ehmatthes** [comment]
I was thinking this would need to go in the friendly deployment summary, but it's short enough that it can probably go in the success messages as well.

**Comment by glasnt** [comment]
Ah, I haven't started looking into the implementations, so I didn't realise these were different things
