### ISSUE TITLE
[New platform support]: Cloud Run

### ISSUE THREAD

**Issue by glasnt** [ehmatthes/django-simple-deploy#193]
### Platform

[Cloud Run](https://cloud.run/)

### Your connection

[Senior Developer Relations Engineer at Google Cloud](https://cloud.google.com/developers/advocates/katie-mclaughlin?hl=en)

### Rationale

Django has been supported on Google Cloud since the first DjangoCon, and Cloud Run is the latest generation of this technology. 

I personally have been working towards helping folks on Google Cloud run Django, but I'd love to be able to flip that on it's head, and help Django folks run on Google Cloud :)

Since Google Cloud is Infrastructure as a Service, there will be a few more products in play that will help with different parts of the deployment (Cloud SQL for the database, Secret Manager for secrets, etc). These will be described as we go.

### CLI arguments

Not mandatory but: database specs

A minimum size postgres database in [Cloud SQL](https://cloud.google.com/sql) has a minimum cost, but it is also small enough that it takes longer than other platforms so far just to provision the initial database (for smaller Django installations, this size of database runs fine). 

Either bumping the minimum database size, or providing a way to adjust this, will make for a faster deployment, but a larger minimum cost.

### Quick Start: Configuration-only deployment

* Create a Google Cloud project
* Enable billing
* `gcloud auth login`

### Technical notes

* settings.py: 
  * adding the service URL to ALLOWED_HOSTS
  * whitenoise configuration
  * database_url based on envvar (provided by [Secret Manager](https://cloud.google.com/secret-manager) while running on Google Cloud)
* Procfile
  * create or update the Procfile, providing commands for deploying, migrating, and collectstatic[0]
  * possibly also createsuperuser, and other admin commands
* `cloudbuild.yaml`
  * a configuration file to run steps in Cloud Build (CI/CD)

[0] https://cloud.google.com/blog/topics/developers-practitioners/running-database-migrations-cloud-run-jobs

### Authentication issues

As long as the user is logged into `gcloud` with their user account on their selected project, they will have the `Owner` role, which enough permissions to create all the elements on that project

### Implementing support for `--automate-all`

Yes, a fully automated deployment is possible, by encoding it all into that `cloudbuild.yaml`. 

### Followup support

Using `cloudbuild.yaml`!

Either directly: `gcloud builds submit`

Or, if we create a [Cloud Source Repo](https://cloud.google.com/source-repositories/docs) (private Git repo), a `git push` to the main branch could trigger this for us (though this would be a Cloud Build trigger that fires separately, rather than a git server hook event, meaning you wouldn't get deployment output to the terminal without an extra step. ([There are ways around this](https://cloud.google.com/blog/topics/developers-practitioners/push-your-code-and-see-your-builds-happening-your-terminal-git-deploy) :) )

### Ongoing maintenance

👋 

I own [samples](https://github.com/GoogleCloudPlatform/avocano) that do their own periodic testing, so I can setup something like this for this new platform.

**Comment by glasnt** [comment]
Other things that the template didn't ask me about, or other design questions

 * Creating a super user
   * Last I checked there wasn't a standard requirement to have this, but for [other samples](https://github.com/GoogleCloudPlatform/avocano/blob/main/server/store/migrations/0001_create_superuser.py) I've written data migrations. This is probably not appropriate for `django-simple-deploy`, so might have to use another method (see previous TODO)
 *  Git repo
    *  Creating a private git repo vs using whatever the user has would only be a n-th deploy difference of `git push` vs `gcloud builds submit`. I personally use GitHub repos for my dev, but `django-simple-deploy` doesn't weigh in on this, and only cares that it's a git repo. I prefer the later, but I have tested the former and know it works.

**Comment by glasnt** [comment]
From the issue template, for my own reference: 

> Since there isn't formal documentation about building out support for a new platform yet, here's a brief description of what it would take:
> 
> - Implementing support
>     - [ ] Add a new directory to `simple_deploy/management/commands/`. The name of this directory should be the same name you want people to use in the command `manage.py simple_deploy --platform PLATFORM_NAME`.
>     - [ ] Add your platform arg to `_validate_platform_arg()` in `simple_deploy.py`. This should be the only change necessary to `simple_deploy.py`.
>     - [ ] In `cli.py`, add your platform arg as an option for the `--platform` argument. This is informational; validation happens in `simple_deploy.py`.
>     - [ ] Write a `deploy.py` script. Using the script from the `fly_io/` folder is probably a good approach at this point.
>     - [ ] Write a `deploy_messages.py` file for any platform-specific output messages you'll need.
>     - [ ] Include a `templates/` directory in your platform's folder for any new files that will need to be created, or any sections that need to be added to existing files.
> - Unit Testing
>     - [ ] Add a new folder in `unit_tests/platforms/` for your platform.
>     - [ ] Make a `reference_files/` directory, and add any test files you need here.
>     - [ ] Write a new file for your platform, called `test_PLATFORMNAME_config.py`. It should test that the sample project is configured correctly when run against your platform. Again, use `test_flyio_config.py` as a template.
> - Integration Testing
>     - [ ] Add a new file to `integration_tests/` called `test_PLATFORMNAME_deployment.sh`. Running `./integration_tests/test_deploy_process.sh -p PLATFORM_NAME` should carry out a full deployment which pops up in a new browser tab, and runs the functionality tests for the sample project.
> - Documentation
>     - [ ] Add a Quick Start page for your platform.
>     - [ ] Add this platform to the home page.
>     - [ ] Add an entry about this platform on the Choosing a Platform page.
> 
> For more information, see [General Approach to Supporting Platforms](https://github.com/ehmatthes/django-simple-deploy/blob/main/old_docs/supporting_platforms.md). This is in `old_docs/`, so it may be somewhat out of date, but it should still be helpful. It will be fully updated and moved to the official documentation at some point before the 1.0 release.
>

**Comment by glasnt** [comment]
Design question: when to provision things

Looking at fly_io, the `_create_db` command is called only within `validate_platform`, specifically because [fly_io takes action based on automate_all in _validate_platform](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/simple_deploy.py#L74)

To copy this pattern, I'll do my provisioning in `validate_all`. 

Provisioning required: 

 * Database
 * Secrets

Post deployment provisioning
 
 * Jobs ((iirc) image has to exist to create a job against it)

**Comment by glasnt** [comment]
Also considering the order of operations for simple things like the `ON_[platform]` envvar. 

In other platforms, the app is a higher order object in the project hierarchy. Some platforms create an app, then configure it. 

In Google Cloud, you have to start with an account (ofc) and a project. Then you'd create elements in that project, including the cloud run service, database, etc. 

Creating a secret in the project is one thing, but assigning that value to the service is another. So when the first command of 2 out of three current platforms is setting a secret, the service needs to exist first. 

This is easily done: 

`gcloud run deploy django --image gcr.io/cloudrun/hello`

Given `gcloud` has been configured with `project` and `run/region`. `hello` is generated from https://github.com/googlecloudplatform/cloud-run-hello 

This will create a service `django` in the region specified, then we can configure the service from there. 

Nomenclature: a Cloud Run service has one or more Revisions. Each Revision is basically a version of the service. Deploying an update creates a new revisions. Revisions can be rolled back. A newly created service has one revision. Each revision references it's own image, so you can absolutely (and some platform automations do) create a placeholder revision that is then updated with a new image.

**Comment by glasnt** [comment]
_On service names_

For other platforms, the app names are generated (e.g. `twilight_leaf_NNNN` for fly.io, or `ancient_crag_NNNNN` for heroku). 

For Cloud Run, the service name can be anything, but the resulting URL will be unique for the service, project, and region. 

So the service could just be something static like `django`. Or, it could be based on the project_name that simple-deploy users. 

In simple_deploy it's based on the ROOT_URLCONF, which itself is based on the project name that was created in django (most often through `django-admin startproject`). Validation on that management command is that the project must be an identifier ([source](https://github.com/django/django/commit/c716fe87821df00f9f03ecc761c914d1682591a2#diff-a33ba212ff6747b54a58d47d932d89e37301d225ba12aa6f6d369aa02176198fR221)), via the method on strings `isidentifier()`, as in a [python identifier](https://docs.python.org/3/reference/lexical_analysis.html#identifiers). 

Python identifiers are: "the uppercase and lowercase letters A through Z, the underscore _ and, except for the first character, the digits 0 through 9."

Cloud Run service identifiers are different, however. "Service name may only start with a letter and contain up to 49 lowercase letters, numbers or hyphens" (via https://console.cloud.google.com/run/create). 

So instead of `django`, the Cloud Run service name could be `self.project_name.replace("_","-")[:49]`.

**Comment by glasnt** [comment]
Most of the steps required in the complex parts of deploy.py will be based on the [Cloud Run Button automations from unicodex](https://github.com/GoogleCloudPlatform/django-demo-app-unicodex/tree/latest/.gcloud). Unicodex has multiple deployment methods, including Terraform, but this version is all script/`gcloud` driven, so it is at least a complete set of steps required to take an empty project to a Django deployment

Some alterations, of course. Such as the [self-csrf](https://github.com/GoogleCloudPlatform/avocano/blob/main/docs/admin/django-self-csrf.md) method, where I can use the [metadata service](https://cloud.google.com/run/docs/container-contract#metadata-server) and default environment variables to reconstruct the service's own URL (does require run.services.get permission, but I think by default we'll be using the Default Compute service account, so that extra step isn't needed)

**Comment by ehmatthes** [comment]
Thanks for submitting this! I'll respond to the template contents in this first comment:

> Django has been supported on Google Cloud since the first DjangoCon

This was really interesting to read!

> Not mandatory but: database specs

I'm not opposed to this at all. I ran into this issue when working through a trial Azure deployment process, and I won't be surprised to see it again on other platforms. I think we can name a parameter that should be usable across multiple platforms, maybe `db_size` or `db_plan`?

> Quick Start: Configuration-only deployment
> Create a Google Cloud project
> Enable billing
> gcloud auth login

What happens after they log in? Would users need to create a remote project before running `manage.py simple_deploy --platform google_cloud_run`, without `--automate-all`? What would they need to do after issuing the `simple_deploy` command? Usually they need to commit changes, and then run a `push` or `deploy` command, and then maybe one last command to open the project.

> possibly also createsuperuser, and other admin commands

I don't really see this as something in the scope of simple_deploy's work. I'm open to a conversation about this, but I've always seen this as a post-deployment step. I'm sure that's because I haven't always used the admin site, so I've often created projects without ever using a superuser. It's important to tell users how to carry out tasks like this, but I'm not sure we want to automate that.

**Comment by glasnt** [comment]
> What happens after they log in? Would users need to create a remote project before running manage.py simple_deploy --platform google_cloud_run, without --automate-all? 


By "remote project" do you mean a remote git repo? 

> What would they need to do after issuing the simple_deploy command? Usually they need to commit changes, and then run a push or deploy command, and then maybe one last command to open the project.

In this case, the deploy command would be `gcloud builds submit`. By default this command runs the steps defined in a `cloudbuild.yaml` file, which are a repeatable set of steps to do deployment. [Example cloudbuild.yaml](https://github.com/GoogleCloudPlatform/avocano/blob/main/cloudbuild.yaml). In this case, the cloudbuild.yaml file would: build the django project into a container, push it to the container registry in the project, apply database migrations, collect static, and deploy the new version of the Cloud Run service. 

> I don't really see this as something in the scope of simple_deploy's work. [..]  It's important to tell users how to carry out tasks like this, but I'm not sure we want to automate that.

Fair enough, I'll just have to make sure I have clear instructions, and may need to setup a helper to assist that.

**Comment by ehmatthes** [comment]
> Git repo
> Creating a private git repo vs using whatever the user has would only be a n-th deploy difference of git push vs gcloud builds submit. I personally use GitHub repos for my dev, but django-simple-deploy doesn't weigh in on this, and only cares that it's a git repo. I prefer the later, but I have tested the former and know it works.

I've focused initially on deployment processes that don't require a push to GitHub. I would be tempted to build this out using the local->cloud run process, and then consider adding an option to use GitHub as an intermediary. From what you're describing, that's how I imagine it would have to be structured anyway, or something similar to that?

> Design question: when to provision things

The guiding principle is to order steps from least significant to most significant, so that if we have to bail we've changed the project, and their remote resources, as little as possible. That basically breaks down to:
- least significant: inspecting the project
    - If we bail, their project is unchanged.
- moderately significant: making local changes
    - If we bail, they may have to roll back local changes.
- most significant: creating remote resources
    - If we bail, they will have new resources on the remote platform that they'll have to deal with. If they try to deploy again, they may end up with multiple resources. This is what we most critically want to avoid.

So, if you can put off provisioning anything until after all local changes have been made, that's ideal. It's usually not possible, because you need to create and then inspect remote resources in order to carry out the configuration process.

**Comment by glasnt** [comment]
> I've focused initially on deployment processes that don't require a push to GitHub. I would be tempted to build this out using the local->cloud run process, and then consider adding an option to use GitHub as an intermediary. From what you're describing, that's how I imagine it would have to be structured anyway, or something similar to that?

You _can_ use GitHub, but Google Cloud offers it's own private git repos, through Cloud Source Repositories. That could be setup like a heroku remote, the problem being that a deployment would be a `git push`, then another command to tail the logs of the triggered build (I describe this a bit more in the "Followup support" part of the OP)

**Comment by ehmatthes** [comment]
I tabled the Azure script because it only worked with `--automate-all`. When I tried to describe the configuration-only approach for end users, it required them to build a number of resources and coordinate them and then run simple_deploy. I ended up feeling like simple_deploy was not actually simplifying the process meaningfully, unless you use the `--automate-all` flag.

I dropped Azure because it was clear that targeting some more Heroku-style platforms was a better use of initial development time. I think someone with a better understanding of the Azure ecosystem would have an easier time building out support. But Azure also runs into the "cheapest resources don't work well" issue.

**Comment by glasnt** [comment]
The complexity jump from PaaS to IaaS is absolutely a cliff for usability. I'm hoping that with my expertise I can help show the "happy path" for this platform, and the minimum steps required (of course without sacrificing security).

**Comment by ehmatthes** [comment]
There's one more important thing I should bring up as you're starting to write the deploy script. Another early contributor suggested we consider restructuring simple_deploy.py to use a plugin-based architecture. That conversation happened over email because they didn't want to publicly suggest a big rewrite, but I think it's a good conversation to have.

Regardless of whether simple_deploy uses a plugin-based approach, a clear goal is to encapsulate all platform-specific code and resources. As I was working through #188, I had the same thought of using a plugin approach even for the platforms that are within the simple_deploy package. Basically, the plugin approach enforces a clean interface between the platform-agnostic and platform-specific interfaces.

This change could be done post-1.0, but if it's going to happen it should certainly be done before many more platforms are supported.

As the first person besides me building out support for a new platform, do you have a clear opinion on this?

**Comment by ehmatthes** [comment]
> I'm hoping that with my expertise I can help show the "happy path" for this platform, and the minimum steps required (of course without sacrificing security).

I'm happy to see you try this integration because I think simple_deploy does have relevance beyond PaaS approaches. I'd love to see a simple_deploy integration for general VPS services such as Digital Ocean and Linode (DO droplets, not their PaaS offering specifically). I've followed the "get Django running on Ubuntu" recipes many times, and wished the entire process was just scripted.

There are a huge number of options for platforms like VPSes and IaaS offerings, but I believe most of them do have "happy paths" that are better starting places than a long page of rote instructions. The value of building off a working initial state is huge.

**Comment by glasnt** [comment]
> As the first person besides me building out support for a new platform, do you have a clear opinion on this?

I presume by plugins you mean splitting this one package into multiple. 

You've said you'd want the process of deployment to only use the concepts that have been learnt already. If by plugins you mean that a user might have to `pip install django-simple-deploy[platform]` rather than `pip install django-simple-deploy` to install additional helper packages, that might just be within presumed knowlege. You would have to explain extras. 

From a maintainer perspective, you've got a structure in the other platforms for the methods that must be implemented (even if that's currently just "Methods called from simple_deploy.py"). This is working well for me, the only problem I'm having is working out, as you mentioned earlier, how to fail fastest, and which actions are taken as configuration vs provisioning. 

If you had separate plugins as separate github repos, you could give platform experts the authority on those sections, but if you're the only maintainer then you can already go that with [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) on separate folders.

**Comment by ehmatthes** [comment]
Please let me know if you need anything, you are the first person with eyes on most of the internals. I am well aware of avoiding premature optimization, but also recognize that it's easier to make some changes earlier than later. If you identify platform-agnostic changes that aren't necessary for cloud run, but would be good for the project, please bring them up or note them in whatever way seems appropriate.

Thanks again!

**Comment by glasnt** [comment]
One of the benefits of IaaS is that you have a lot of control about how things are named, and how to get data about the things that exist. For example, based on my earlier comment above about service names, I can ensure that any things I do create are mapped against the current django project (I could also use tagging, or other mechanisms). 

I will definitely let you know how I progress. I'll continue to leave myself notes in this issue as I go.

**Comment by ehmatthes** [comment]
Thanks, that's helpful for thinking about other platforms as well.

**Comment by glasnt** [comment]
Development cycle: 

Setup:

 * Fork https://github.com/glasnt/django-simple-project, removing remote
 * Add simple-deploy to INSTALLED_APPS
 * Commit change
 * Create virtualenv, `pip install -e /path/to/django-simple-deploy`
 
Loop: 

 * try `python manage.py simple_deploy --platform cloudrun --automate-all`
 * when it breaks, address
 * `git stash && rm .gitignore simple_deploy_logs/ -r`

**Comment by glasnt** [comment]
From the cli_reference: 

`--automate-all`

 * " The recommended way to use simple_deploy is in **configuration** mode. In this mode, simple_deploy makes all configuration changes necessary to successfully deploy your project on the given platform. it does not commit these changes, it does not create any resources on your behalf". 
   * I'll have to confirm exactly what other platforms do here, because there are some things that must exist before I can do some configurations. 
     * Specifically because looking at the quickstarts, doing configuration only does actually do some platform resource creation. E.g. fly.io configuration only "will create a database"   

`--deployed-project-name DEPLOYED_PROJECT_NAME` 
 
 * By default, `simple_deploy` tries to use the same name you used when you ran `django-admin startproject PROJECT_NAME`
   * see "On service names" earlier, we can attempt this, with `s/_/-`. 
  
 `--region` 

   * make sure I include this.    

`--unit/integration-testing`
  
   * yet to handle/look at

**Comment by ehmatthes** [comment]
> Specifically because looking at the quickstarts, doing configuration only does actually do some platform resource creation. E.g. fly.io configuration only "will create a database"

You are correct. I will clarify the language in the cli reference. (See #194)

**Comment by glasnt** [comment]
At the moment, I'm trying to balance in my head the minimum resources vs minimum _paid_ resources. 

Specifically, if someone does a configuration run and comes back later, they won't have ongoing costs. 

Going by the `[platform]_success_msg`s, the platforms currently get you to manually `[platform] deploy` if you don't automate. 

I'm thinking for this, if we're in configuration mode, my steps that create resources could instead write those commands to a file, that the `success_msg` could then report back to the user saying "run these, then [platform] deploy". That way there's explicit "here's what you'll need to create", while generating the commands for the user based on the project.

**Comment by glasnt** [comment]
On regions: 

I originally had simple_deploy configure the default region for the user by configuring it in `gcloud`. This is not appropriate, as simple_deploy shouldn't make changes to the user's setup that could affect things outside of simple_deploy. 

Instead, for region I'll get it from the param passed, or if configured from the cli, or otherwise choose a default, and store the value in the class. I have to be explicit about region for most things anyway, so there's not many usability improvements this feature would have added.

**Comment by glasnt** [comment]
I've got most of it working, haven't started any tests yet, but it mostly runs clean. 

https://github.com/glasnt/django-simple-deploy/tree/feat/cloudrun

**Comment by ehmatthes** [comment]
> At the moment, I'm trying to balance in my head the minimum resources vs minimum paid resources.
> Specifically, if someone does a configuration run and comes back later, they won't have ongoing costs.

I've been thinking a lot about this. One of the main challenges for me in thinking around this has been what to do if a configuration is only partially completed. Configuring from a blank slate is straightforward as long as we're willing to be opinionated; configuring from a partially-configured project is much harder.

I think it might be good to explicitly state that we always expect to configure from a blank slate. For example, on Fly.io that means assuming that no database exists for the project, so we'll create one each time `simple_deploy` is run. That's much more straightforward and reliable than trying to poll existing databases and trying to figure out if one is connected to the current project. We can consider bailing if we find configuration that already exists for the current platform. We'd post a message reporting what we found, and making a suggestion about how to get back to a clean state. To be clear, by "clean slate" I mean a locally working Django project with no platform-specific configuration or settings. Some things might not require bailing, ie maybe they wrote their own `Procfile` and that's okay?

The main reason so far to promote the configuration-only approach is to avoid creating remote resources and making commits on the user's behalf if we don't have to. That's not always possible, so it's quite reasonable to create resources, even paid resources, as long as we're being clear to the user before (ie in quick start guides and confirmation messages) what we're going to create on their behalf.

> I'm thinking for this, if we're in configuration mode, my steps that create resources could instead write those commands to a file, that the success_msg could then report back to the user saying "run these, then [platform] deploy". That way there's explicit "here's what you'll need to create", while generating the commands for the user based on the project.

If this works, that might be a reasonable approach. I would be cautious about asking the user to run a command with specific resource names. ie if the command they have to run is `cli create db`, and the cli automatically creates a database connected to this app, that would probably be fine. If the command they have to run is `cli create db --name VERY_SPECIFIC_NAME`, and that name has to match the name of another resource, that's the kind of opportunity for typos that this whole project aims to prevent.

> Update: the only really intrusive resource is the database, which has a confirmation check if not in --automate-all (like flyio)

**Comment by ehmatthes** [comment]
> I've got most of it working, haven't started any tests yet, but it mostly runs clean.

I would be happy to try a deployment when you like how it's working, before you write any tests.

**Comment by glasnt** [comment]
If my configuration is suggesting names for resources where the name doesn't matter (isn't public facing, is just an implementation detail), then I can at least have consistency. 

One of the things my platform implementation currently has is limited repeatability. For example, if it finds an SQL instance of a specific name, it will continue. This has greatly helped me with iterative development, as this is the longest part of the deployment. (Though so far I have used 5 fresh projects, for various reasons from "Let me try running this though clean" to "What did I break oh no"). 

---

I'm going to be starting some long-needed leave until the new year shortly, but I'll try and fix the issue I noted above, and let you know when this is ready for a not-me test.

**Comment by glasnt** [comment]
Just infra things:

```
django.core.exceptions.ImproperlyConfigured: The database name '/cloudsql/glasnt-simpledeploy5-8139:us-central1:mysite-instance/django-db' (73 characters) is longer than PostgreSQL's limit of 63 characters. 
```

🫠

(The way around this is to make the instance name static, and/or shorter, and check length ahead of time)

**Comment by glasnt** [comment]
Just infra things:

```
django.core.exceptions.ImproperlyConfigured: The database name 
'/cloudsql/glasnt-simpledeploy5-NNNN:us-central1:mysite-instance/django-db' (73 characters) is longer
than PostgreSQL's limit of 63 characters. 
```

🫠

(The way around this is to make the instance name static, and/or shorter, and check length ahead of time)

**Comment by ehmatthes** [comment]
> I'm going to be starting some long-needed leave until the new year shortly.

No rush, enjoy your leave! I'm going to work on supporting poetry and pipenv across the existing platforms. If I make any significant changes by the time this gets merged, I'm happy to help with any updates based on new changes to the platform-agnostic parts of the project.

**Comment by glasnt** [comment]
I didn't realise there would be issues with `dj-database-url` and Cloud SQL. 

I use `django-environ` in my projects, which will parse out a connection string: 

```
(Pdb) import environ
(Pdb) env = environ.Env()
(Pdb) env.db()
{'NAME': 'sd-db', 
'USER': 'django', 
'PASSWORD': '[redacted]', 
'HOST': '/cloudsql/[redacted]:us-central1:sd-inst', 
'PORT': '', 
'ENGINE': 'django.db.backends.postgresql'}
```

But the same thing in dj-database-url gets issues: 

```

(Pdb) db_url = os.environ.get("DATABASE_URL")
(Pdb) dj_database_url.parse(db_url)
{'NAME': '/cloudsql/[redacted]:us-central1:sd-inst/sd-db', 
'USER': 'django', 
'PASSWORD': '[redacted]', 
'HOST': '', 
'PORT': '', 
'CONN_MAX_AGE': 0, 
'ENGINE': 'django.db.backends.postgresql'}
```

This is a known issue: https://github.com/jazzband/dj-database-url/issues/132, and it looks like there's a currently active PR https://github.com/jazzband/dj-database-url/pull/181 that should fix this.

**Comment by glasnt** [comment]
Okay, before I step away, progress update.

 * v1.1.0 of dj-database-url didn't include the fix mentioned above, though it's now in the main branch. The workaround I've marked can be removed once this new release is cut.
 * I'm not used to dj-database-url, so there's currently an issue with the setup there, but I'll work it out quickly.
 * I realised I missed creating the SECRET_KEY (because my test app hardcodes it), so I recently broke out the secret creation logic into it's own reusable bit, so it's a bit untested (e.g. currently doesn't check before creating, for example)
 * I should really test this with not-my-simple-sample, to make sure it handles things more robustly (e.g. another demo project of mine, the sample project in the repo, an example that actually reads from the database 😅 )

Latest code pushed to my fork.

**Comment by ehmatthes** [comment]
FYI there are some significant changes coming to the way we handle the user's package management system. Responding to the user's package management system was being handled inconsistently, with some work being done in simple_deploy.py and some left to the platform-specific script. That's a leftover from targeting Heroku initially and then expanding to more platforms.

The newer approach is to only identify the package management script in simple_deploy.py, and let each platform decide how to respond. simple_deploy.py has a new method `add_pkg()`, which then delegates to scripts that add the package in the appropriate way. So adding a package for most platforms is as simple as `self.sd.add_pkg("whitenoise")`. There will also likely be a method `self.sd.add_packages()` that lets you add all necessary packages at once.

Some platforms can't handle whatever package management system the user has chosen, and we need to convert to a requirements specification approach that the platform supports. For example last I looked into it Heroku accepts requirements.txt and Pipfile, but does not recognize poetry.lock. So when a project is using poetry, we generate a requirements.txt file for Heroku. That's done in simple_deploy.py currently, but that work is moving to Heroku's script so other platforms can work directly with Poetry. (The heroku script will likely generate a requirements.txt file when using Poetry, and then manually override the identified value of `self.sd.pkg_manager`.) That's good, because we don't want to clutter the user's requirements specification approaches if not necessary, ie we don't want to add a requirements.txt file when they're relying on poetry.lock.

All of this work is being done on the `restructure_pkg_man` branch, and tracked in #202. It should be straightforward to update your work to use these changes, and most importantly it lets you choose how to handle whatever package management system the user has chosen. I will be happy to talk you through any changes that have landed by the time you come back to this.

The next release should handle requirements.txt, Poetry, and Pipenv on macOS and Linux. There's still a lot of work to do, but 1.0 feels a lot closer. Once Windows is fully supported, this becomes a much more useful library to a wide range of users. :)

**Comment by glasnt** [comment]
> FYI there are some significant changes coming to the way we handle the user's package management system. 

\o/

> Some platforms can't handle whatever package management system the user has chosen, and we need to convert to a requirements specification approach that the platform supports. For example last I looked into it Heroku accepts requirements.txt and Pipfile, but does not recognize poetry.lock. So when a project is using poetry, we generate a requirements.txt file for Heroku. That's done in simple_deploy.py currently, but that work is moving to Heroku's script so other platforms can work directly with Poetry. (The heroku script will likely generate a requirements.txt file when using Poetry, and then manually override the identified value of `self.sd.pkg_manager`.) That's good, because we don't want to clutter the user's requirements specification approaches if not necessary, ie we don't want to add a requirements.txt file when they're relying on poetry.lock.

This sounds similar to what I'd need here. Currently the [Cloud Buildpacks](https://cloud.google.com/docs/buildpacks/python) documentation only mentions pip/`requirements.txt`. 
 
> All of this work is being done on the `restructure_pkg_man` branch, and tracked in #202. It should be straightforward to update your work to use these changes, and most importantly it lets you choose how to handle whatever package management system the user has chosen. I will be happy to talk you through any changes that have landed by the time you come back to this.

Awesome. 


> The next release should handle requirements.txt, Poetry, and Pipenv on macOS and Linux. There's still a lot of work to do, but 1.0 feels a lot closer. Once Windows is fully supported, this becomes a much more useful library to a wide range of users. :)

I'm absolutely happy to own whatever refactor needed for my platform with these changes. I have the capacity to test all OSs as well, so that's also useful!

Note to self: I'm very interested to see how the package usage is different in 2022 compared to the 2021 survey https://lp.jetbrains.com/python-developers-survey-2021/#PythonPackaging I didn't realise pipenv was so highly used.

**Comment by glasnt** [comment]
On superuser: 

Sometimes I think I know what I'm doing with Django

Then I find out that `createsuperuser --noinput` has been around since 3.0 (late 2019). 

This means I don't have to do things with data migrations or other nonsense, I can just create a secret, and a job that references that secret as an envvar to do an adhoc management command job (the structure for which is now published over on https://cloud.google.com/blog/topics/developers-practitioners/running-database-migrations-cloud-run-jobs)

**Comment by glasnt** [comment]
Okay. I think I have a minimum working platform. 

Pending: 

 * `python test_deployed_app_functionality.py --url (deployed url)` fails
    * but only because the sample app in the project has `DEBUG = True` and the  test suit fails on "Checking that DEBUG is set to False correctly."
 * Working out how to run the unit/integration tests for one specific platform
    * I currently take copies of example apps (my simple-project, the unnested sample project), `git init .` and add `simple_deploy` to `INSTALLED_APPS`, and in the case of the sample project remove the `Pipfile` and `pyproject.toml` (add_package was adding to Pipfile, and Cloud Run only uses `requirements.txt`, so the deployment failed. 
 * Work out if I should move the class attribute to the `__init__`. 
   * If I reorder operations I end up with undeclared variables, but no other platform uses the `__init__`.   

Results of a completely uninterrupted run, on 6de56b2: 

```
$ python manage.py simple_deploy --platform cloudrun --automate-all
...
$ python test_deployed_app_functionality.py --url https://blog-v7qyrd6maq-uc.a.run.app

Testing functionality of deployed app at https://blog-v7qyrd6maq-uc.a.run.app/...

  Checking anonymous home page...
  Checking empty anonmyous all_blogs page...
  Checking empty anonmyous latest_posts page...
  Checking that anonymous my_blogs page redirects to login...
  Checking that anonymous register page is available...
  Checking that anonymous login page is available...
  Checking that admin static assets are available...
  Checking that a user account can be made, and checking the logged-in version of the home page...
  Checking that a public blog can be created, and that it's visible to owner...
  Checking that a public post on public blog is visible to owner...
  Checking that a private post on public blog is visible to owner...
  Checking that a private blog can be created, and that it's visible to owner...
  Checking that a public post on private blog is visible to owner...
  Checking that the logout process works...
  Checking that public blog is visible to an anonymous user...
  Checking that private blog is not visible to anonymous user...
  Checking that public post is visible on public blog...
  Checkig that private post is not visible on public blog...
  Checking that public post on private blog is not visible...
  Checking style on login form...
  Checking that DEBUG is set to False correctly. ---
Traceback (most recent call last):
  File "/path/to/test_deployed_app_functionality.py", line 395, in <module>
    assert "Not Found" in r.text
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by ehmatthes** [comment]
> `python test_deployed_app_functionality.py --url (deployed url) fails`

Yes, this has been annoying me for a while, but I haven't made time to address it. It's logged in #195, which is about cleaning up the integration testing process overall.

Running unit tests *should* be pretty straightforward at this point, but if it's not please don't hesitate to ask.

**Comment by glasnt** [comment]
A brief look at unit testing...

The test for me were failing poorly using the [docs](), but after looking at the currently in draft [ci setup PR](https://github.com/ehmatthes/django-simple-deploy/pull/182/files) it explicitly installs the platform CLIs. 

Given I have a new laptop, I didn't have (in this case) `flyctl` installed, so the entire `pytest platforms/fly_io` failed hard. But after a `brew install flyctl`, it ran green. 

Suggestion: maybe add a blocking test for dependencies that fails the platform suite if not installed?

Also: is there a way to disable pipenv/poetry tests, or should I be supporting these by using Dockefiles (currently using Procfile for pip but I can absolutely change this)

**Comment by ehmatthes** [comment]
> The test for me were failing poorly using the [docs](https://github.com/ehmatthes/django-simple-deploy/issues/193), but after looking at the currently in draft [ci setup PR](https://github.com/ehmatthes/django-simple-deploy/pull/182/files) it explicitly installs the platform CLIs.

Yes, I had to install the CLI for each platform during development work, so it didn't occur to me that people would be testing on systems without the CLI installed.

> Suggestion: maybe add a blocking test for dependencies that fails the platform suite if not installed?

This is a great suggestion; see #209.

> Also: is there a way to disable pipenv/poetry tests, or should I be supporting these by using Dockefiles (currently using Procfile for pip but I can absolutely change this)

Not through the CLI yet, but there's a single line of code you can modify in conftest.py that will have the same effect. See the workaround in #210.

But I'm not sure that answers your question. Each platform should support a user who's using poetry locally, even if the platform doesn't use poetry to install dependencies. For example the Heroku deploy.py file has a `handle_poetry()` method, that generates a requirements.txt file and then sets `pkg_manager` to req_txt.  We test Heroku against a project that uses Poetry; how the Heroku deployer handles that is its own business.

**Comment by ehmatthes** [comment]
I believe this is stale; feel free to reopen it as needed. Note that the plugin model, which should be landing fairly soon, should make this kind of work much more straightforward.

**Comment by glasnt** [comment]
I am very much interested in re-visiting this once a plugin model is available.
