### ISSUE TITLE
Notes from sprints at PyCon US 2023

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#215]
A few people are helping, so here's a few notes from the table conversation:

- [x] Push fix for #217.
- [x] Fly uses `flyctl` and `fly` interchangeably. Add a note to the Fly Quick Start clarifying this. (Fly notes they are moving to `fly` as the preferred usage.)
- [ ] Add `(b_env)` to [contributing test run](https://django-simple-deploy.readthedocs.io/en/latest/contributing/test_run/) docs.
- [ ] In heroku quick_start, include a reference to git commit.
- [x] Update changelog as needed.
- [ ] Fix failed test_deployed_app_functionality.py issue with local testing for `DEBUG = False`.
- [ ] Start a contributors.md doc.
- [x] In setting up dev env doc, I believe I left a placeholder in the clone command.
- [x] Consider using GitHub CLI, especially around working with PRs.
- [x] Merge contributions to comparison page, and then clean up for consistency.
- [ ] Add venv terminal prompt indicators in Setting up a dev environment.

**Comment by mjsir911** [comment]
Oh, when setting up via fly.io, creating a new account asked me for a credit card, contrary to documentation within this project.

Repro:
- go to fly.io
- press the free trial button
- create account through github
- I believe at this point fly.io asked me for a credit card to "verify" my legitimacy or something. Recalling this from memory.

**Comment by mjsir911** [comment]
Here's where I'm blocked in the process currently:
- have successfully installed `flyctl`, set up a django project (with a `requirements.txt`! as specified as required)
- ```bash
  $ flyctl apps create --generate-name
  automatically selected personal organization: Marco Sirabella
  New app created: shy-surf-1761
  ```
- ```
  $ python manage.py simple_deploy --platform fly_io
  Configuring project for deployment...
    Deployment target: fly_io
  
  ***** Deployments to Fly.io are experimental at this point ***
  
  - Support for deploying to Fly.io is in an exploratory phase at this point.
  - You should only be using this project to deploy to Fly.io at this point if
    you are interested in helping to develop or test the simple_deploy project.
  - You should look at the deploy_flyio.py script before running this command,
    so you know what kinds of changes will be made to your project.
  - This command will likely fail if you run it more than once.
  - This command may not work if you already have a project deployed to Fly.io.
  - You should understand the Fly.io console, and be comfortable deleting resources
    that are created during this deployment.
  - You may want to cancel this run and deploy to a different platform.
  
  Are you sure you want to do this? (yes|no) 
  yes
    Continuing with Fly.io deployment...
    Found .git dir at /tmp/tmp.73qD13X5tj/django-crud-example.
    Dependency management system: req_txt
    Checking current project requirements...
      Found existing dependencies:
        django
        django-simple-deploy
        
  
  Looking for Fly.io app to deploy against...
  CommandError: 
  A Fly.io app name could not be found.
  
  The simple_deploy command expects that you've already created an app on Fly.io
  to push to.
  
  If you haven't done so, run the following command to create a new Fly.io app:
  
      $ flyctl apps create --generate-name
  
  Then run simple_deploy again.
  ```
