### ISSUE TITLE
Documenting a Test Run for fly.io

### ISSUE THREAD

**Issue by darjeeling** [ehmatthes/django-simple-deploy#220]
Before completing the test run:
- What OS are you using?

Mac 13.3.1(22E261) M1 mac air

- What project are you deploying? (the sample blog project, or your own project?)
own project

- If you're not deploying the sample blog project, can you provide a link to the project you're working with?
https://github.com/pythonkr/pyconkr-api-v2
devdev branch

- What dependency management system are you using?
`req_txt`

- Which platform are you targeting?
fly.io testing

After you complete the test run, please answer the following questions in a followup comment:
- What worked well?
  - creating app on fly.io
- What did not work well?
  - deployment it self.
  - error message is 
```Looking for Fly.io region...
CommandError:
--- A Fly.io region was not found. ---

We need to know what region the app is going to be deployed to.
We could not find a region in the output of:

$ flyctl regions list -a ${PROJECT_NAME}
```
- What suggestions do you have for the project based on your test run?
  - I think we need to add more free platform to new people can use this.
    - digitalocean's app gave some coupon to start
    - aws lambda is free when you have very small request with serverless database
  - also need to warn with pricing and dashboard link 
- What questions do you have about the project based on your test run?

**Comment by ehmatthes** [comment]
Thank you again for this test run, it's helpful to see which issues are one-off issues and which are persistent. Closing this, as it will be resolved by #256.
