### ISSUE TITLE
FAILED when running heroku poetry unittest

### ISSUE THREAD

**Issue by darjeeling** [ehmatthes/django-simple-deploy#223]
problem on running `pytest platforms/heroku`

```
FAILED platforms/heroku/test_heroku_config.py::test_settings[poetry] - AssertionError 
```

I looked at the error and find out there is problem in copying files on my environment.

I'm using `pyenv` with `virtualenv `

errors maybe occurred on shell script `utils/setup_project.sh`

looks like
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pyenv: cannot change working directory to `/private/var/folders/98/n2p054fd2ms1rd1f569p5rw40000gn/T/pytest-of-dj/pytest-13/blog_project0/blog'
```

**Comment by darjeeling** [comment]
I tested with changing params
```
@pytest.fixture(scope='module', params=["req_txt", "poetry", "pipenv"])
```

only `poetry` failed

**Comment by ehmatthes** [comment]
You are using macOS, right?

**Comment by darjeeling** [comment]
@ehmatthes yes. latest version. M1

**Comment by ehmatthes** [comment]
I'm going to comment about this topic on #230.

**Comment by ehmatthes** [comment]
After getting rid of all shell scripts in the unit tests (#236), I'm going to close this issue. If you still have an issue running unit tests, please open a new issue. Thanks!
