### ISSUE TITLE
Heroku CLI Windows Installation

### ISSUE THREAD

**Issue by lopesgluiz** [ehmatthes/django-simple-deploy#227]
**Problem:**
- After installing the heroku cli in windows i couldn't use any of the command in the windows terminal
- In the windows installation i checked the option to add to the path

If that also happened to you one way around it would be to manually add in the Path varaibles:
- Go to: Settings->Advanced System Settings->Environment Variables
- Click in Path and in Edit
- Click in "New" on the right side of the Edit Environment Variables window
- Add the path that heroku was installed in your system, in my case was: "C:\Program Files\Heroku\bin"
- You can also check this post in [stackoverflow](https://stackoverflow.com/questions/44301515/heroku-cli-installation-error-path-not-updated-original-length-1585-1024#:~:text=You%20should%20also%20try%20to,will%20manually%20update%20the%20PATH.)

**Comment by ehmatthes** [comment]
Closing, as this seems to be more about the Heroku CLI than django-simple-deploy.
