### ISSUE TITLE
Errors when running "python manage.py simple_deploy --platform [platform-name]" on windows

### ISSUE THREAD

**Issue by lopesgluiz** [ehmatthes/django-simple-deploy#231]
**Context:**
- After cloning the [sample repo](https://github.com/ehmatthes/dsd_sample_blog_reqtxt)
- Setting up the virtual environment
- Installing all its dependencies ("pip install -r requirements.txt")
- When trying to deploy the sample app to Heroku Platform i executed the following commands:
  - $ pip install django-simple-deploy
  - Add "simple_deploy" to INSTALLED_APPS in settings.py.
  - $ git commit -am "Added simple_deploy to INSTALLED_APPS.**
  - $ heroku create
  - $ python manage.py simple_deploy --platform heroku

**Problem:**
- After the last command simple_deploy should analyze the requirements.txt file and add the packages needed by the Django deploy in the [heroku platform](https://devcenter.heroku.com/articles/deploying-python) but instead is adding the following message to the requirements.txt file:

਍橤湡潧猭浩汰ⵥ敤汰祯†††††‣摁敤⁤祢猠浩汰彥敤汰祯挠浯慭摮മ朊湵捩牯⁮††††††††††⌠䄠摤摥戠⁹楳灭敬摟灥潬⁹潣浭湡⹤਍獰捹灯㉧†††††††††††‣摁敤⁤祢猠浩汰彥敤汰祯挠浯慭摮മ搊⵪慤慴慢敳甭汲†††††††⌠䄠摤摥戠⁹楳灭敬摟灥潬⁹潣浭湡⹤਍桷瑩湥楯敳††††††††††‣摁敤⁤祢猠浩汰彥敤汰祯挠浯慭摮 

- Probably the error is caused due to the lack of encoding when the packages are being appended to 'requirements.txt'

**To Do's:**

- [ ] Fix the encoding problem
- [ ] Add tests to this issue
- [ ] Verify if the problem affects the appending in mac, linux, etc.

**Comment by ehmatthes** [comment]
Thanks, this is great! We'll pick this up tomorrow morning. :)

**Comment by ehmatthes** [comment]
I believe this is fixed with #237. If it's not, feel free to reopen this issue, or open a new issue.
