### ISSUE TITLE
Update unit tests to run entirely within Python, and not use any shell scripts

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#233]
I originally wrote tests in bash, because it's a much quicker development process, and easier to modify during development. The drawback is it doesn't work on any systems that use a different terminal environment. I am hoping that this update makes the unit tests work on all terminal environments on all OSes. Because there are a bunch of shell commands being called from within Python though, I'm guessing there will still be some updating to do. But that should be easier from within Python, than from a shell script that just plain doesn't work on some systems.

One nice thing to keep in mind for this work, is that almost all assertions are already made in Python. So any changes to the setup work that don't affect the overall passing of tests, are unlikely to break any tests. I only mention this because I will probably use gpt to assist with the conversion of shell scripts. I'm wary of relying on AI tools to generate tests, because if they subtly change what's tested then the test suite is less reliable. Using AI to assist in updating test setup is much less risky than using AI to make and modify actual assertions.

## Main tasks

- [x] Replace setup_project.sh with a Python function, to clarify how to approach this work.
- [x] Replace other shell scripts with Python functions.
- [x] Update docs/ understanding the unit tests.
    - I will do this, and this will not block merging the PR for the code. If I don't have time to update this doc, I'll just put a note at the top that the shell scripts have been replaced with Python code.)
- [ ] Note in contributing docs that a good first PR is to make sure unit tests pass on your system. Then upgrade all packages in the sample project, and update all reference files to match these versions. The only changed files in the PR should be requirements.txt in the sample project, and reference files corresponding to these in the unit_tests dir. Note how to update vendor/.

**Comment by ehmatthes** [comment]
u/darjeeling, I was planning to do this work, but you sound interested in doing it. Do you want to take this on, or do you want me to do it? I was looking forward to doing this, but if you're ready to dive in I would welcome that. 

If you're interested, can you share a little about how you would approach it? I started it this weekend and used gpt to automate the conversion from shell scripts to Python, but I only had 10 minutes and didn't have the chance to fully implement it.

**Comment by darjeeling** [comment]
@ehmatthes I think we can start from these

1. convert small git scripts to python utility class for starting point
2. convert start and reset project

it's ok. we don't have much time to do that. so we can start small and with shellscript exist both time.

**Comment by ehmatthes** [comment]
Benchmarks
---

Unit tests don't take excessively long now, but they will only grow as the project matures. Any efficiencies we find now will be helpful in the long run as well, even if they only save a second or two off the current time. These tests are being done on a 2019 intel mac, and the raw numbers are only meaningful for me.  The % improvements should be relevant to anyone running unit tests.

```sh
$ time pytest -x
```
```

**Comment by ehmatthes** [comment]
Replace setup_project.sh with a Python function
---

```sh
% pytest platform_agnostic_tests/test_valid_cli_commands.py -x
```

- My `setup_project()` function completes all of its tasks.
- However, test fails at `sh: utils/reset_test_project.sh: No such file or directory`

**Comment by ehmatthes** [comment]
Notes
---

- [ ] Add docstrings to gpt generated code.
- [ ] Add comments to gpt generated code.

~3s to make venv during test setup; any optimizations here are really helpful

**Comment by ehmatthes** [comment]
Fly.io unit tests
---

- [ ] It's running simple_deploy, but it's not getting the project name?
```python
if os.environ.get("ON_FLYIO"):
    # These settings need to be in place during deployment, but not during
    #   the setup process.
    # The `dj_database_url.parse()` call causes the build to fail; other settings
    #   here may not.
    import dj_database_url
    
    # Use secret, if set, to update DEBUG value.
    if os.environ.get("DEBUG") == "FALSE":
        DEBUG = False
    elif os.environ.get("DEBUG") == "TRUE":
        DEBUG = True

    # Set a Fly.io-specific allowed host.
    ALLOWED_HOSTS.append('.fly.dev')

    # Use the Fly.io Postgres database.
    db_url = os.environ.get("DATABASE_URL")
    DATABASES['default'] = dj_database_url.parse(db_url)

    # Prevent CSRF "Origin checking failed" issue.
    CSRF_TRUSTED_ORIGINS = ['https://.fly.dev']
```

**Comment by ehmatthes** [comment]
Final cleanup
---

- [ ] All tests pass.
- [ ] For each shell script, copy comments to relevant Python function, add any other relevant comments, remove script, and make sure all tests still pass:
    - [ ] setup_project.sh
    - [ ] reset_project.sh
    - [ ] commit_test_project.sh
    - [ ] call_simple_deploy.sh
    - [ ] call_simple_deploy_invalid.sh
    - [ ] call_git_status.sh
    - [ ] call_git_log.sh
- [ ] Check that poetry is installed before running tests.
- [ ] Check that Pipenv is installed before running tests.
- [ ] Skip check for CLIs:
    - [ ] Fly.io
    - [ ] Platform.sh
- [ ] Update docs based on above notes.
- [ ] Make sure tests pass on newer computer.
- [ ] Update changelog.
- [ ] PR & merge.
- [ ] Ask someone else to try running unit tests.
- [ ] Try running unit tests in a Windows VM.

**Comment by ehmatthes** [comment]
Bonus cleanup
---

- [ ] Refactor manage_test_project.py into helper module.

**Comment by ehmatthes** [comment]
Merged; no release necessary. Remaining tasks moved to #235.
