### ISSUE TITLE
Ongoing unit test improvements

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#235]
Most of these are left over from 233, which is ready to be closed.

- [ ] Note in contributing docs that a good first PR is to make sure unit tests pass on your system. Then upgrade all packages in the sample project, and update all reference files to match these versions. The only changed files in the PR should be requirements.txt in the sample project, and reference files corresponding to these in the unit_tests dir. Note how to update vendor/.
- [ ] Consider defining some paths initially, to be available everywhere: sd_proj_dir, unit_test_dir, and tmp_proj_dir
- [ ] Try running unit tests in a Windows VM.
- [ ] Refactor manage_test_project.py into helper module.
- [ ] Continue to look for ways to make unit tests run faster, particularly in the first ~10s when it's setting up the sample project for the first time.
- [ ] Consider setting an `on_windows` flag, or something similar, if I'm checking `sys.platform == 'win32'` often.
- [x] Write a plugin that opens the test project after a failed test. Should: open a new terminal tab, cd to the tmp dir, activate the venv, and maybe run `git log --pretty=oneline`. Should complain if not run with the `-x` flag, as that's the only meaningful time to poke around the test project. #240

**Comment by ehmatthes** [comment]
@darjeeling the unit tests are now entirely written in Python. If you have a chance, will you see if they run on your system? I have one system that uses just the macOS Python installer from python.org, and one that uses pyenv. The tests run on both of these systems. I'm curious if you will see any issues. I haven't tried it on Windows yet.

**Comment by ehmatthes** [comment]
Speeding up tests
---

- From a bit of diagnostic work, I can see pytest is spending no meaningful time finding tests, even if it is looking in more directories than it needs to. It shows "collected items" very quickly, and begins setting up for the first test. Most optimization efforts should probably focus on how we work with the sample project.

**Comment by darjeeling** [comment]
I tested with 1b75ca4c14906461a6cc2f92a1231422dbe064c4

I looks fine.

```
(djangosimpledeploy) ➜  unit_tests git:(main) ✗ pytest
============================================= test session starts ==============================================
platform darwin -- Python 3.11.3, pytest-7.0.1, pluggy-1.0.0
rootdir: /Users/dj/github/darjeeling/django-simple-deploy
collected 93 items

platform_agnostic_tests/test_invalid_cli_commands.py .........                                           [  9%]
platform_agnostic_tests/test_project_inspection.py sss                                                   [ 12%]
platform_agnostic_tests/test_valid_cli_commands.py ...                                                   [ 16%]
platforms/fly_io/test_flyio_config.py ...........................                                        [ 45%]
platforms/heroku/test_heroku_config.py ...........................                                       [ 74%]
platforms/platform_sh/test_platformsh_config.py ........................                                 [100%]

======================================== 90 passed, 3 skipped in 19.12s ========================================
```

**Comment by ehmatthes** [comment]
Thanks, that's helpful to know!
