### ISSUE TITLE
Execute simple_deploy --automate-all two time for the same projet

### ISSUE THREAD

**Issue by rickavmaniac** [ehmatthes/django-simple-deploy#27]
Hi,

When I execute the python manage.py simple_deploy --automate-all for the second time in the same project, I got an error

in _get_heroku_app_info
    raise CommandError(dh_msgs.no_heroku_app_detected)
NameError: name 'CommandError' is not defined

Is there a way to reset and start all over ?

By the way thanks for your work. Great package!

**Comment by ehmatthes** [comment]
Hi, I just opened an issue to address this generally (#14), but I will try to help you through your situation.

- What made you run it a second time? Was there a specific error the first time you ran it?
- I think calling `heroku create` a second time just creates another heroku app.
    - Did you see any output indicating that happened?
    - If you look at your Heroku dashboard do you see two recently-created apps?
    - Are you at the max number of apps?
- Is this a public project that I can look at?

The clearest way to start over is to use git to roll back to the commit before you ran simple_deploy. Then go to your Heroku dashboard and delete any apps that were created by simple_deploy calling `heroku create`. That should bring you back to where you were before using simple_deploy.

**Comment by rickavmaniac** [comment]
> Hi, I just opened an issue to address this generally (#28), but I will try to help you through your situation.
> 
> * What made you run it a second time? Was there a specific error the first time you ran it?
> * I think calling `heroku create` a second time just creates another heroku app.
>   

First time I run everything was ok. Then I delete the app on Heroku side, then I try to relanch the install and that where the error happend.

>   * Did you see any output indicating that happened?

Yes the install try to create a new app everything I launch the install with simple_deploy --automate-all 

>   * If you look at your Heroku dashboard do you see two recently-created apps?
Yes
>   * Are you at the max number of apps?
No
> * Is this a public project that I can look at?
No sorry
> 
> The clearest way to start over is to use git to roll back to the commit before you ran simple_deploy. Then go to your Heroku dashboard and delete any apps that were created by simple_deploy calling `heroku create`. That should bring you back to where you were before using simple_deploy.

Ok will do that. 

Once the app is deploy, is there a way to update this app ? What's the command for that ?

Thanks for your work

**Comment by ehmatthes** [comment]
> First time I run everything was ok. Then I delete the app on Heroku side

Okay, this means your project was fully configured for deploying to Heroku. The only thing that's specific to a particular deployment is the `ALLOWED_HOSTS` setting. So to deploy again, you should be able to run `heroku create` to start a new app; then add this new app's url to `ALLOWED_HOSTS` in the heroku-specific section of settings.py. Commit your changes, and run `git push heroku main`, assuming your main branch is called `main`.

Here's the [message](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/utils/deploy_messages_heroku.py#L74) that should be displayed after a successful push. It tells you how to make successive deployments. Did you see this message? One of the features I'll implement in the near future is logging, so if you miss this message in the cli output, you can still see it in a neatly-formatted log file.

**Comment by ehmatthes** [comment]
I don't think there's anything more to do outside the new issues that this has brought up.
