### ISSUE TITLE
Try uv for testing?

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/django-simple-deploy#291]
Tests are slow because of the need to build a virtual environment for the test suite. Try replacing pip with uv, and see if it's a meaningful improvement.

- [ ] Drop uv in for pip, benchmark.
- [ ] If there's an improvement, are there any tradeoffs in complexity/ stability?

**Comment by joshuadavidthomas** [comment]
Chiming in that I've completely replaced `pip` with `uv` throughout all of my work and personal projects and have not seen any stability issues. It honestly could be as simple as a search and replace `s/pip/uv pip/g` throughout the code base.

**Comment by ehmatthes** [comment]
I'm quite clear how this would benefit me, and how I would start using uv. I'm less clear about how to specify it as a requirement for the project. Would I just add it to the project requirements?

For example, what happens if someone has installed uv through Homebrew, and then they clone simple_deploy and install from requirements. Would pip recognize that uv is already available, or would they have their brew uv and a pip-installed uv in this project environment?
