### ISSUE TITLE
Static files not charged (Style)

### ISSUE THREAD

**Issue by princeGedeon** [ehmatthes/django-simple-deploy#93]
Very good job. But there is a problem with the static files at home. My styles do not load otherwise the automation is perfect

**Comment by ehmatthes** [comment]
Thanks for the report. Can you offer any additional information for troubleshooting? What OS are you using? What platform did you deploy to? Is this a public project that I can look at?

**Comment by ehmatthes** [comment]
I'm closing this as it's almost two weeks now, but feel free to reopen if you want a further response.
